/*
  Saved responses from below API calls:
  https://launch.smarthealthit.org/v/r4/fhir/Patient/bc6c8e2a-63de-4790-94af-fcab57874c21
  https://launch.smarthealthit.org/v/r4/fhir/Observation?patient=bc6c8e2a-63de-4790-94af-fcab57874c21&_count=100&_sort=-date&code=http%3A%2F%2Floinc.org%7C8462-4%2Chttp%3A%2F%2Floinc.org%7C8480-6%2Chttp%3A%2F%2Floinc.org%7C2085-9%2Chttp%3A%2F%2Floinc.org%7C2089-1%2Chttp%3A%2F%2Floinc.org%7C55284-4%2Chttp%3A%2F%2Floinc.org%7C3141-9%2Chttp%3A%2F%2Floinc.org%7C8302-2%2Chttp%3A%2F%2Floinc.org%7C29463-7
  https://launch.smarthealthit.org/v/r4/fhir/MedicationRequest?patient=bc6c8e2a-63de-4790-94af-fcab57874c21
*/

export const charitaAdams = {
  patient: {
    "resourceType": "Patient",
    "id": "bc6c8e2a-63de-4790-94af-fcab57874c21",
    "meta": {
      "versionId": "2",
      "lastUpdated": "2019-06-05T02:52:51.828-04:00",
      "tag": [
        {
          "system": "https://smarthealthit.org/tags",
          "code": "synthea-5-2019"
        }
      ]
    },
    "text": {
      "status": "generated",
      "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by <a href=\"https://github.com/synthetichealth/synthea\">Synthea</a>.Version identifier: v2.4.0-100-g26a4b936\n .   Person seed: -2246297879569217994  Population seed: 1559319163074</div>"
    },
    "extension": [
      {
        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race",
        "extension": [
          {
            "url": "ombCategory",
            "valueCoding": {
              "system": "urn:oid:2.16.840.1.113883.6.238",
              "code": "2028-9",
              "display": "Asian"
            }
          },
          {
            "url": "text",
            "valueString": "Asian"
          }
        ]
      },
      {
        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity",
        "extension": [
          {
            "url": "ombCategory",
            "valueCoding": {
              "system": "urn:oid:2.16.840.1.113883.6.238",
              "code": "2186-5",
              "display": "Not Hispanic or Latino"
            }
          },
          {
            "url": "text",
            "valueString": "Not Hispanic or Latino"
          }
        ]
      },
      {
        "url": "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
        "valueString": "Shawnta Reichert"
      },
      {
        "url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
        "valueCode": "F"
      },
      {
        "url": "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
        "valueAddress": {
          "city": "Beijing",
          "state": "Beijing Municipality",
          "country": "CN"
        }
      },
      {
        "url": "http://synthetichealth.github.io/synthea/disability-adjusted-life-years",
        "valueDecimal": 0
      },
      {
        "url": "http://synthetichealth.github.io/synthea/quality-adjusted-life-years",
        "valueDecimal": 19
      }
    ],
    "identifier": [
      {
        "system": "https://github.com/synthetichealth/synthea",
        "value": "6400dfb2-5b5b-4ff7-be37-d041edefb208"
      },
      {
        "type": {
          "coding": [
            {
              "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
              "code": "MR",
              "display": "Medical Record Number"
            }
          ],
          "text": "Medical Record Number"
        },
        "system": "http://hospital.smarthealthit.org",
        "value": "6400dfb2-5b5b-4ff7-be37-d041edefb208"
      },
      {
        "type": {
          "coding": [
            {
              "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
              "code": "SS",
              "display": "Social Security Number"
            }
          ],
          "text": "Social Security Number"
        },
        "system": "http://hl7.org/fhir/sid/us-ssn",
        "value": "999-50-9640"
      },
      {
        "type": {
          "coding": [
            {
              "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
              "code": "DL",
              "display": "Driver's License"
            }
          ],
          "text": "Driver's License"
        },
        "system": "urn:oid:2.16.840.1.113883.4.3.25",
        "value": "S99951155"
      }
    ],
    "name": [
      {
        "use": "official",
        "family": "Adams",
        "given": [
          "Charita"
        ],
        "prefix": [
          "Ms."
        ]
      }
    ],
    "telecom": [
      {
        "system": "phone",
        "value": "555-325-5612",
        "use": "home"
      }
    ],
    "gender": "female",
    "birthDate": "1999-11-13",
    "address": [
      {
        "extension": [
          {
            "url": "http://hl7.org/fhir/StructureDefinition/geolocation",
            "extension": [
              {
                "url": "latitude",
                "valueDecimal": 42.323853
              },
              {
                "url": "longitude",
                "valueDecimal": -71.142002
              }
            ]
          }
        ],
        "line": [
          "261 Zboncak Row Apt 6"
        ],
        "city": "Brookline",
        "state": "Massachusetts",
        "postalCode": "02215",
        "country": "US"
      }
    ],
    "maritalStatus": {
      "coding": [
        {
          "system": "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
          "code": "S",
          "display": "Never Married"
        }
      ],
      "text": "Never Married"
    },
    "multipleBirthBoolean": false,
    "communication": [
      {
        "language": {
          "coding": [
            {
              "system": "urn:ietf:bcp:47",
              "code": "zh",
              "display": "Chinese"
            }
          ],
          "text": "Chinese"
        }
      }
    ]
  },
  observation: {
    "resourceType": "Bundle",
    "id": "7b8e0120-3e66-46f6-a2c7-fc9d24448a43",
    "meta": {
      "lastUpdated": "2021-03-26T20:48:33.090-04:00"
    },
    "type": "searchset",
    "total": 30,
    "link": [
      {
        "relation": "self",
        "url": "https://launch.smarthealthit.org/v/r4/fhir/Observation?_count=100&_sort=-date&code=http%3A%2F%2Floinc.org%7C8462-4%2Chttp%3A%2F%2Floinc.org%7C8480-6%2Chttp%3A%2F%2Floinc.org%7C2085-9%2Chttp%3A%2F%2Floinc.org%7C2089-1%2Chttp%3A%2F%2Floinc.org%7C55284-4%2Chttp%3A%2F%2Floinc.org%7C3141-9%2Chttp%3A%2F%2Floinc.org%7C8302-2%2Chttp%3A%2F%2Floinc.org%7C29463-7&patient=bc6c8e2a-63de-4790-94af-fcab57874c21"
      }
    ],
    "entry": [
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/049b16d0-3869-4460-bfad-4903de1a22ad",
        "resource": {
          "resourceType": "Observation",
          "id": "049b16d0-3869-4460-bfad-4903de1a22ad",
          "meta": {
            "versionId": "2",
            "lastUpdated": "2019-06-05T02:56:04.776-04:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "8302-2",
                "display": "Body Height"
              }
            ],
            "text": "Body Height"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/f1e6ae96-f5c8-41b9-9acb-5c6ed1d11838"
          },
          "effectiveDateTime": "2018-11-24T10:07:51-05:00",
          "issued": "2018-11-24T10:07:51.313-05:00",
          "valueQuantity": {
            "value": 161.69713092909043,
            "unit": "cm",
            "system": "http://unitsofmeasure.org",
            "code": "cm"
          }
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"2\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/c4050063-ee4f-4126-ab63-64ffd7e22e5b",
        "resource": {
          "resourceType": "Observation",
          "id": "c4050063-ee4f-4126-ab63-64ffd7e22e5b",
          "meta": {
            "versionId": "5",
            "lastUpdated": "2020-10-05T03:02:25.406-04:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "55284-4",
                "display": "Blood Pressure"
              }
            ],
            "text": "Blood Pressure"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/f1e6ae96-f5c8-41b9-9acb-5c6ed1d11838"
          },
          "effectiveDateTime": "2018-11-24T10:07:51-05:00",
          "issued": "2018-11-24T10:07:51.313-05:00",
          "component": [
            {
              "code": {
                "coding": [
                  {
                    "system": "http://loinc.org",
                    "code": "8462-4",
                    "display": "Diastolic Blood Pressure"
                  }
                ],
                "text": "Diastolic Blood Pressure"
              },
              "valueQuantity": {
                "value": 78.49950793576159,
                "unit": "mm[Hg]",
                "system": "http://unitsofmeasure.org",
                "code": "mm[Hg]"
              }
            },
            {
              "code": {
                "coding": [
                  {
                    "system": "http://loinc.org",
                    "code": "8480-6",
                    "display": "Systolic Blood Pressure"
                  }
                ],
                "text": "Systolic Blood Pressure"
              },
              "valueQuantity": {
                "value": 105.34173005274555,
                "unit": "mm[Hg]",
                "system": "http://unitsofmeasure.org",
                "code": "mm[Hg]"
              }
            }
          ]
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"5\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/c1d7df5a-51c4-43a5-bca4-61b42cb18d97",
        "resource": {
          "resourceType": "Observation",
          "id": "c1d7df5a-51c4-43a5-bca4-61b42cb18d97",
          "meta": {
            "versionId": "214",
            "lastUpdated": "2021-03-25T02:59:08.221-04:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "29463-7",
                "display": "Body Weight"
              }
            ],
            "text": "Body Weight"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/f1e6ae96-f5c8-41b9-9acb-5c6ed1d11838"
          },
          "effectiveDateTime": "2018-11-24T10:07:51-05:00",
          "issued": "2018-11-24T10:07:51.313-05:00",
          "valueQuantity": {
            "value": 56.040089187569926,
            "unit": "kg",
            "system": "http://unitsofmeasure.org",
            "code": "kg"
          }
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"214\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/e9bef4c1-9864-48ee-8c1a-95f4f46cddb2",
        "resource": {
          "resourceType": "Observation",
          "id": "e9bef4c1-9864-48ee-8c1a-95f4f46cddb2",
          "meta": {
            "versionId": "2",
            "lastUpdated": "2019-06-05T02:54:25.170-04:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "55284-4",
                "display": "Blood Pressure"
              }
            ],
            "text": "Blood Pressure"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/d59a0fab-3e9c-4e39-b1f1-188273744f1e"
          },
          "effectiveDateTime": "2017-11-18T10:07:51-05:00",
          "issued": "2017-11-18T10:07:51.313-05:00",
          "component": [
            {
              "code": {
                "coding": [
                  {
                    "system": "http://loinc.org",
                    "code": "8462-4",
                    "display": "Diastolic Blood Pressure"
                  }
                ],
                "text": "Diastolic Blood Pressure"
              },
              "valueQuantity": {
                "value": 78.7549317838391,
                "unit": "mm[Hg]",
                "system": "http://unitsofmeasure.org",
                "code": "mm[Hg]"
              }
            },
            {
              "code": {
                "coding": [
                  {
                    "system": "http://loinc.org",
                    "code": "8480-6",
                    "display": "Systolic Blood Pressure"
                  }
                ],
                "text": "Systolic Blood Pressure"
              },
              "valueQuantity": {
                "value": 134.44315334243132,
                "unit": "mm[Hg]",
                "system": "http://unitsofmeasure.org",
                "code": "mm[Hg]"
              }
            }
          ]
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"2\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/0c4e9187-00cf-49d7-bd10-abaa0507aeb7",
        "resource": {
          "resourceType": "Observation",
          "id": "0c4e9187-00cf-49d7-bd10-abaa0507aeb7",
          "meta": {
            "versionId": "13",
            "lastUpdated": "2021-03-08T01:57:40.582-05:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "29463-7",
                "display": "Body Weight"
              }
            ],
            "text": "Body Weight"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/d59a0fab-3e9c-4e39-b1f1-188273744f1e"
          },
          "effectiveDateTime": "2017-11-18T10:07:51-05:00",
          "issued": "2017-11-18T10:07:51.313-05:00",
          "valueQuantity": {
            "value": 54.88101018728409,
            "unit": "kg",
            "system": "http://unitsofmeasure.org",
            "code": "kg"
          }
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"13\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/a1b69874-25e8-4758-b7d4-20e85b4fdd8a",
        "resource": {
          "resourceType": "Observation",
          "id": "a1b69874-25e8-4758-b7d4-20e85b4fdd8a",
          "meta": {
            "versionId": "2",
            "lastUpdated": "2019-06-05T03:00:08.555-04:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "8302-2",
                "display": "Body Height"
              }
            ],
            "text": "Body Height"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/d59a0fab-3e9c-4e39-b1f1-188273744f1e"
          },
          "effectiveDateTime": "2017-11-18T10:07:51-05:00",
          "issued": "2017-11-18T10:07:51.313-05:00",
          "valueQuantity": {
            "value": 161.555646413398,
            "unit": "cm",
            "system": "http://unitsofmeasure.org",
            "code": "cm"
          }
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"2\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/756c7f25-23cd-41e0-bbd9-2d7b65131019",
        "resource": {
          "resourceType": "Observation",
          "id": "756c7f25-23cd-41e0-bbd9-2d7b65131019",
          "meta": {
            "versionId": "9",
            "lastUpdated": "2021-03-08T01:59:42.930-05:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "29463-7",
                "display": "Body Weight"
              }
            ],
            "text": "Body Weight"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/442fbeee-94e2-460f-9867-e8b93ed1168d"
          },
          "effectiveDateTime": "2016-11-12T10:07:51-05:00",
          "issued": "2016-11-12T10:07:51.313-05:00",
          "valueQuantity": {
            "value": 53.84139903938695,
            "unit": "kg",
            "system": "http://unitsofmeasure.org",
            "code": "kg"
          }
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"9\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/52866c08-4612-4f08-9e89-f7a0109b450b",
        "resource": {
          "resourceType": "Observation",
          "id": "52866c08-4612-4f08-9e89-f7a0109b450b",
          "meta": {
            "versionId": "2",
            "lastUpdated": "2019-06-05T02:56:32.258-04:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "8302-2",
                "display": "Body Height"
              }
            ],
            "text": "Body Height"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/442fbeee-94e2-460f-9867-e8b93ed1168d"
          },
          "effectiveDateTime": "2016-11-12T10:07:51-05:00",
          "issued": "2016-11-12T10:07:51.313-05:00",
          "valueQuantity": {
            "value": 161.34039992798935,
            "unit": "cm",
            "system": "http://unitsofmeasure.org",
            "code": "cm"
          }
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"2\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/8fa18a3f-efff-4ca9-916d-ae0e8f25e2d4",
        "resource": {
          "resourceType": "Observation",
          "id": "8fa18a3f-efff-4ca9-916d-ae0e8f25e2d4",
          "meta": {
            "versionId": "2",
            "lastUpdated": "2019-06-05T02:58:46.329-04:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "55284-4",
                "display": "Blood Pressure"
              }
            ],
            "text": "Blood Pressure"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/442fbeee-94e2-460f-9867-e8b93ed1168d"
          },
          "effectiveDateTime": "2016-11-12T10:07:51-05:00",
          "issued": "2016-11-12T10:07:51.313-05:00",
          "component": [
            {
              "code": {
                "coding": [
                  {
                    "system": "http://loinc.org",
                    "code": "8462-4",
                    "display": "Diastolic Blood Pressure"
                  }
                ],
                "text": "Diastolic Blood Pressure"
              },
              "valueQuantity": {
                "value": 76.44822744900561,
                "unit": "mm[Hg]",
                "system": "http://unitsofmeasure.org",
                "code": "mm[Hg]"
              }
            },
            {
              "code": {
                "coding": [
                  {
                    "system": "http://loinc.org",
                    "code": "8480-6",
                    "display": "Systolic Blood Pressure"
                  }
                ],
                "text": "Systolic Blood Pressure"
              },
              "valueQuantity": {
                "value": 109.82918642307246,
                "unit": "mm[Hg]",
                "system": "http://unitsofmeasure.org",
                "code": "mm[Hg]"
              }
            }
          ]
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"2\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/363909e8-8234-4888-bbd2-157367c75d1a",
        "resource": {
          "resourceType": "Observation",
          "id": "363909e8-8234-4888-bbd2-157367c75d1a",
          "meta": {
            "versionId": "9",
            "lastUpdated": "2021-03-08T01:58:32.600-05:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "29463-7",
                "display": "Body Weight"
              }
            ],
            "text": "Body Weight"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/8afd1835-1882-4025-9155-854ecb587493"
          },
          "effectiveDateTime": "2015-11-07T10:07:51-05:00",
          "issued": "2015-11-07T10:07:51.313-05:00",
          "valueQuantity": {
            "value": 52.54782783297707,
            "unit": "kg",
            "system": "http://unitsofmeasure.org",
            "code": "kg"
          }
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"9\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/7e3c79a6-78ab-4e37-82aa-a5ee599f25bd",
        "resource": {
          "resourceType": "Observation",
          "id": "7e3c79a6-78ab-4e37-82aa-a5ee599f25bd",
          "meta": {
            "versionId": "2",
            "lastUpdated": "2019-06-05T03:00:01.751-04:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "55284-4",
                "display": "Blood Pressure"
              }
            ],
            "text": "Blood Pressure"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/8afd1835-1882-4025-9155-854ecb587493"
          },
          "effectiveDateTime": "2015-11-07T10:07:51-05:00",
          "issued": "2015-11-07T10:07:51.313-05:00",
          "component": [
            {
              "code": {
                "coding": [
                  {
                    "system": "http://loinc.org",
                    "code": "8462-4",
                    "display": "Diastolic Blood Pressure"
                  }
                ],
                "text": "Diastolic Blood Pressure"
              },
              "valueQuantity": {
                "value": 89.87587277011092,
                "unit": "mm[Hg]",
                "system": "http://unitsofmeasure.org",
                "code": "mm[Hg]"
              }
            },
            {
              "code": {
                "coding": [
                  {
                    "system": "http://loinc.org",
                    "code": "8480-6",
                    "display": "Systolic Blood Pressure"
                  }
                ],
                "text": "Systolic Blood Pressure"
              },
              "valueQuantity": {
                "value": 131.17803532392068,
                "unit": "mm[Hg]",
                "system": "http://unitsofmeasure.org",
                "code": "mm[Hg]"
              }
            }
          ]
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"2\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/260bb54c-7982-4008-9971-445df6655e4f",
        "resource": {
          "resourceType": "Observation",
          "id": "260bb54c-7982-4008-9971-445df6655e4f",
          "meta": {
            "versionId": "2",
            "lastUpdated": "2019-06-05T02:58:16.979-04:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "8302-2",
                "display": "Body Height"
              }
            ],
            "text": "Body Height"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/8afd1835-1882-4025-9155-854ecb587493"
          },
          "effectiveDateTime": "2015-11-07T10:07:51-05:00",
          "issued": "2015-11-07T10:07:51.313-05:00",
          "valueQuantity": {
            "value": 160.96804625370365,
            "unit": "cm",
            "system": "http://unitsofmeasure.org",
            "code": "cm"
          }
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"2\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/e78f8bcf-07a5-42b2-b731-850b71d926bb",
        "resource": {
          "resourceType": "Observation",
          "id": "e78f8bcf-07a5-42b2-b731-850b71d926bb",
          "meta": {
            "versionId": "2",
            "lastUpdated": "2019-06-05T02:59:22.201-04:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "8302-2",
                "display": "Body Height"
              }
            ],
            "text": "Body Height"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/5f5dbe3f-1874-417f-aeea-eab8d74962ca"
          },
          "effectiveDateTime": "2014-11-01T11:07:51-04:00",
          "issued": "2014-11-01T11:07:51.313-04:00",
          "valueQuantity": {
            "value": 160.25245987269193,
            "unit": "cm",
            "system": "http://unitsofmeasure.org",
            "code": "cm"
          }
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"2\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/ced7e75b-2a25-4837-abdb-2deacf617814",
        "resource": {
          "resourceType": "Observation",
          "id": "ced7e75b-2a25-4837-abdb-2deacf617814",
          "meta": {
            "versionId": "2",
            "lastUpdated": "2019-06-05T02:55:11.093-04:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "55284-4",
                "display": "Blood Pressure"
              }
            ],
            "text": "Blood Pressure"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/5f5dbe3f-1874-417f-aeea-eab8d74962ca"
          },
          "effectiveDateTime": "2014-11-01T11:07:51-04:00",
          "issued": "2014-11-01T11:07:51.313-04:00",
          "component": [
            {
              "code": {
                "coding": [
                  {
                    "system": "http://loinc.org",
                    "code": "8462-4",
                    "display": "Diastolic Blood Pressure"
                  }
                ],
                "text": "Diastolic Blood Pressure"
              },
              "valueQuantity": {
                "value": 88.83901100155923,
                "unit": "mm[Hg]",
                "system": "http://unitsofmeasure.org",
                "code": "mm[Hg]"
              }
            },
            {
              "code": {
                "coding": [
                  {
                    "system": "http://loinc.org",
                    "code": "8480-6",
                    "display": "Systolic Blood Pressure"
                  }
                ],
                "text": "Systolic Blood Pressure"
              },
              "valueQuantity": {
                "value": 126.44993667869123,
                "unit": "mm[Hg]",
                "system": "http://unitsofmeasure.org",
                "code": "mm[Hg]"
              }
            }
          ]
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"2\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/3d59b09d-a5fd-43ad-af45-4a3d94b84626",
        "resource": {
          "resourceType": "Observation",
          "id": "3d59b09d-a5fd-43ad-af45-4a3d94b84626",
          "meta": {
            "versionId": "7",
            "lastUpdated": "2021-03-08T01:57:05.136-05:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "29463-7",
                "display": "Body Weight"
              }
            ],
            "text": "Body Weight"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/5f5dbe3f-1874-417f-aeea-eab8d74962ca"
          },
          "effectiveDateTime": "2014-11-01T11:07:51-04:00",
          "issued": "2014-11-01T11:07:51.313-04:00",
          "valueQuantity": {
            "value": 50.64514757272426,
            "unit": "kg",
            "system": "http://unitsofmeasure.org",
            "code": "kg"
          }
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"7\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/a115f591-11e7-48f5-893b-404c78212163",
        "resource": {
          "resourceType": "Observation",
          "id": "a115f591-11e7-48f5-893b-404c78212163",
          "meta": {
            "versionId": "2",
            "lastUpdated": "2019-06-05T02:57:49.712-04:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "55284-4",
                "display": "Blood Pressure"
              }
            ],
            "text": "Blood Pressure"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/28fb14fd-d56f-4ca3-af6d-10aa6dc8715b"
          },
          "effectiveDateTime": "2013-10-26T11:07:51-04:00",
          "issued": "2013-10-26T11:07:51.313-04:00",
          "component": [
            {
              "code": {
                "coding": [
                  {
                    "system": "http://loinc.org",
                    "code": "8462-4",
                    "display": "Diastolic Blood Pressure"
                  }
                ],
                "text": "Diastolic Blood Pressure"
              },
              "valueQuantity": {
                "value": 71.39092372076604,
                "unit": "mm[Hg]",
                "system": "http://unitsofmeasure.org",
                "code": "mm[Hg]"
              }
            },
            {
              "code": {
                "coding": [
                  {
                    "system": "http://loinc.org",
                    "code": "8480-6",
                    "display": "Systolic Blood Pressure"
                  }
                ],
                "text": "Systolic Blood Pressure"
              },
              "valueQuantity": {
                "value": 125.88144680449827,
                "unit": "mm[Hg]",
                "system": "http://unitsofmeasure.org",
                "code": "mm[Hg]"
              }
            }
          ]
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"2\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/ea8068c6-8a90-4c48-b6da-da25ea2e81e5",
        "resource": {
          "resourceType": "Observation",
          "id": "ea8068c6-8a90-4c48-b6da-da25ea2e81e5",
          "meta": {
            "versionId": "2",
            "lastUpdated": "2019-06-05T02:54:40.589-04:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "8302-2",
                "display": "Body Height"
              }
            ],
            "text": "Body Height"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/28fb14fd-d56f-4ca3-af6d-10aa6dc8715b"
          },
          "effectiveDateTime": "2013-10-26T11:07:51-04:00",
          "issued": "2013-10-26T11:07:51.313-04:00",
          "valueQuantity": {
            "value": 158.70871035549368,
            "unit": "cm",
            "system": "http://unitsofmeasure.org",
            "code": "cm"
          }
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"2\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/4bd4501e-31f3-49b4-b347-618909797702",
        "resource": {
          "resourceType": "Observation",
          "id": "4bd4501e-31f3-49b4-b347-618909797702",
          "meta": {
            "versionId": "7",
            "lastUpdated": "2021-03-08T01:58:41.306-05:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "29463-7",
                "display": "Body Weight"
              }
            ],
            "text": "Body Weight"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/28fb14fd-d56f-4ca3-af6d-10aa6dc8715b"
          },
          "effectiveDateTime": "2013-10-26T11:07:51-04:00",
          "issued": "2013-10-26T11:07:51.313-04:00",
          "valueQuantity": {
            "value": 47.91893110660537,
            "unit": "kg",
            "system": "http://unitsofmeasure.org",
            "code": "kg"
          }
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"7\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/8534c738-382b-4968-b943-e89c0c1851a9",
        "resource": {
          "resourceType": "Observation",
          "id": "8534c738-382b-4968-b943-e89c0c1851a9",
          "meta": {
            "versionId": "2",
            "lastUpdated": "2019-06-05T02:57:02.232-04:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "55284-4",
                "display": "Blood Pressure"
              }
            ],
            "text": "Blood Pressure"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/56d8e92a-37e5-4c29-9198-39104d61a85f"
          },
          "effectiveDateTime": "2012-10-20T11:07:51-04:00",
          "issued": "2012-10-20T11:07:51.313-04:00",
          "component": [
            {
              "code": {
                "coding": [
                  {
                    "system": "http://loinc.org",
                    "code": "8462-4",
                    "display": "Diastolic Blood Pressure"
                  }
                ],
                "text": "Diastolic Blood Pressure"
              },
              "valueQuantity": {
                "value": 80.43696881914232,
                "unit": "mm[Hg]",
                "system": "http://unitsofmeasure.org",
                "code": "mm[Hg]"
              }
            },
            {
              "code": {
                "coding": [
                  {
                    "system": "http://loinc.org",
                    "code": "8480-6",
                    "display": "Systolic Blood Pressure"
                  }
                ],
                "text": "Systolic Blood Pressure"
              },
              "valueQuantity": {
                "value": 112.51780371714872,
                "unit": "mm[Hg]",
                "system": "http://unitsofmeasure.org",
                "code": "mm[Hg]"
              }
            }
          ]
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"2\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/e2275934-6380-4738-be9a-043ce8e1720a",
        "resource": {
          "resourceType": "Observation",
          "id": "e2275934-6380-4738-be9a-043ce8e1720a",
          "meta": {
            "versionId": "11",
            "lastUpdated": "2021-03-08T01:59:39.624-05:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "29463-7",
                "display": "Body Weight"
              }
            ],
            "text": "Body Weight"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/56d8e92a-37e5-4c29-9198-39104d61a85f"
          },
          "effectiveDateTime": "2012-10-20T11:07:51-04:00",
          "issued": "2012-10-20T11:07:51.313-04:00",
          "valueQuantity": {
            "value": 44.38527915061803,
            "unit": "kg",
            "system": "http://unitsofmeasure.org",
            "code": "kg"
          }
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"11\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/adc5ef3e-cade-476d-a25f-4125fdd6d107",
        "resource": {
          "resourceType": "Observation",
          "id": "adc5ef3e-cade-476d-a25f-4125fdd6d107",
          "meta": {
            "versionId": "2",
            "lastUpdated": "2019-06-05T02:58:53.249-04:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "8302-2",
                "display": "Body Height"
              }
            ],
            "text": "Body Height"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/56d8e92a-37e5-4c29-9198-39104d61a85f"
          },
          "effectiveDateTime": "2012-10-20T11:07:51-04:00",
          "issued": "2012-10-20T11:07:51.313-04:00",
          "valueQuantity": {
            "value": 155.28842630101377,
            "unit": "cm",
            "system": "http://unitsofmeasure.org",
            "code": "cm"
          }
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"2\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/70525bc1-d29c-485c-a206-054a44169ae8",
        "resource": {
          "resourceType": "Observation",
          "id": "70525bc1-d29c-485c-a206-054a44169ae8",
          "meta": {
            "versionId": "2",
            "lastUpdated": "2019-06-05T03:00:03.141-04:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "8302-2",
                "display": "Body Height"
              }
            ],
            "text": "Body Height"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/046d589a-d5a2-4a54-b333-95224edf355f"
          },
          "effectiveDateTime": "2011-10-15T11:07:51-04:00",
          "issued": "2011-10-15T11:07:51.313-04:00",
          "valueQuantity": {
            "value": 148.50410678483613,
            "unit": "cm",
            "system": "http://unitsofmeasure.org",
            "code": "cm"
          }
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"2\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/1a0fc6e3-99e2-4508-ac9c-ea7b179fc506",
        "resource": {
          "resourceType": "Observation",
          "id": "1a0fc6e3-99e2-4508-ac9c-ea7b179fc506",
          "meta": {
            "versionId": "2",
            "lastUpdated": "2019-06-05T02:57:40.372-04:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "55284-4",
                "display": "Blood Pressure"
              }
            ],
            "text": "Blood Pressure"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/046d589a-d5a2-4a54-b333-95224edf355f"
          },
          "effectiveDateTime": "2011-10-15T11:07:51-04:00",
          "issued": "2011-10-15T11:07:51.313-04:00",
          "component": [
            {
              "code": {
                "coding": [
                  {
                    "system": "http://loinc.org",
                    "code": "8462-4",
                    "display": "Diastolic Blood Pressure"
                  }
                ],
                "text": "Diastolic Blood Pressure"
              },
              "valueQuantity": {
                "value": 81.91898493059018,
                "unit": "mm[Hg]",
                "system": "http://unitsofmeasure.org",
                "code": "mm[Hg]"
              }
            },
            {
              "code": {
                "coding": [
                  {
                    "system": "http://loinc.org",
                    "code": "8480-6",
                    "display": "Systolic Blood Pressure"
                  }
                ],
                "text": "Systolic Blood Pressure"
              },
              "valueQuantity": {
                "value": 109.9384238416141,
                "unit": "mm[Hg]",
                "system": "http://unitsofmeasure.org",
                "code": "mm[Hg]"
              }
            }
          ]
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"2\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/4d081fef-9ff2-4109-98e9-19766d8d4071",
        "resource": {
          "resourceType": "Observation",
          "id": "4d081fef-9ff2-4109-98e9-19766d8d4071",
          "meta": {
            "versionId": "5",
            "lastUpdated": "2021-03-08T01:58:10.318-05:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "29463-7",
                "display": "Body Weight"
              }
            ],
            "text": "Body Weight"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/046d589a-d5a2-4a54-b333-95224edf355f"
          },
          "effectiveDateTime": "2011-10-15T11:07:51-04:00",
          "issued": "2011-10-15T11:07:51.313-04:00",
          "valueQuantity": {
            "value": 39.92349244639962,
            "unit": "kg",
            "system": "http://unitsofmeasure.org",
            "code": "kg"
          }
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"5\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/6b00ab20-e5f2-4092-a98d-4bef4b6cc9fc",
        "resource": {
          "resourceType": "Observation",
          "id": "6b00ab20-e5f2-4092-a98d-4bef4b6cc9fc",
          "meta": {
            "versionId": "11",
            "lastUpdated": "2021-03-08T01:59:55.721-05:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "29463-7",
                "display": "Body Weight"
              }
            ],
            "text": "Body Weight"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/8a7b59e6-9431-44b3-b0a7-e5de675fa54b"
          },
          "effectiveDateTime": "2010-10-09T11:07:51-04:00",
          "issued": "2010-10-09T11:07:51.313-04:00",
          "valueQuantity": {
            "value": 35.61211065359437,
            "unit": "kg",
            "system": "http://unitsofmeasure.org",
            "code": "kg"
          }
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"11\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/cd89278d-484b-4f75-962f-28c4d9c3cd1e",
        "resource": {
          "resourceType": "Observation",
          "id": "cd89278d-484b-4f75-962f-28c4d9c3cd1e",
          "meta": {
            "versionId": "2",
            "lastUpdated": "2019-06-05T02:59:09.637-04:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "8302-2",
                "display": "Body Height"
              }
            ],
            "text": "Body Height"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/8a7b59e6-9431-44b3-b0a7-e5de675fa54b"
          },
          "effectiveDateTime": "2010-10-09T11:07:51-04:00",
          "issued": "2010-10-09T11:07:51.313-04:00",
          "valueQuantity": {
            "value": 141.40546300263858,
            "unit": "cm",
            "system": "http://unitsofmeasure.org",
            "code": "cm"
          }
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"2\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/45c9917d-e006-4283-a52c-704883b6047c",
        "resource": {
          "resourceType": "Observation",
          "id": "45c9917d-e006-4283-a52c-704883b6047c",
          "meta": {
            "versionId": "2",
            "lastUpdated": "2019-06-05T02:58:01.572-04:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "55284-4",
                "display": "Blood Pressure"
              }
            ],
            "text": "Blood Pressure"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/8a7b59e6-9431-44b3-b0a7-e5de675fa54b"
          },
          "effectiveDateTime": "2010-10-09T11:07:51-04:00",
          "issued": "2010-10-09T11:07:51.313-04:00",
          "component": [
            {
              "code": {
                "coding": [
                  {
                    "system": "http://loinc.org",
                    "code": "8462-4",
                    "display": "Diastolic Blood Pressure"
                  }
                ],
                "text": "Diastolic Blood Pressure"
              },
              "valueQuantity": {
                "value": 80.70514847164772,
                "unit": "mm[Hg]",
                "system": "http://unitsofmeasure.org",
                "code": "mm[Hg]"
              }
            },
            {
              "code": {
                "coding": [
                  {
                    "system": "http://loinc.org",
                    "code": "8480-6",
                    "display": "Systolic Blood Pressure"
                  }
                ],
                "text": "Systolic Blood Pressure"
              },
              "valueQuantity": {
                "value": 121.86338594595163,
                "unit": "mm[Hg]",
                "system": "http://unitsofmeasure.org",
                "code": "mm[Hg]"
              }
            }
          ]
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"2\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/d7fcfd83-f245-4010-b3b9-764e8295cf4b",
        "resource": {
          "resourceType": "Observation",
          "id": "d7fcfd83-f245-4010-b3b9-764e8295cf4b",
          "meta": {
            "versionId": "2",
            "lastUpdated": "2019-06-05T02:59:19.660-04:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "55284-4",
                "display": "Blood Pressure"
              }
            ],
            "text": "Blood Pressure"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/040b39d3-7162-4d4d-9133-1eb0d2d3df35"
          },
          "effectiveDateTime": "2009-10-03T11:07:51-04:00",
          "issued": "2009-10-03T11:07:51.313-04:00",
          "component": [
            {
              "code": {
                "coding": [
                  {
                    "system": "http://loinc.org",
                    "code": "8462-4",
                    "display": "Diastolic Blood Pressure"
                  }
                ],
                "text": "Diastolic Blood Pressure"
              },
              "valueQuantity": {
                "value": 80.77698475158559,
                "unit": "mm[Hg]",
                "system": "http://unitsofmeasure.org",
                "code": "mm[Hg]"
              }
            },
            {
              "code": {
                "coding": [
                  {
                    "system": "http://loinc.org",
                    "code": "8480-6",
                    "display": "Systolic Blood Pressure"
                  }
                ],
                "text": "Systolic Blood Pressure"
              },
              "valueQuantity": {
                "value": 111.54429504779134,
                "unit": "mm[Hg]",
                "system": "http://unitsofmeasure.org",
                "code": "mm[Hg]"
              }
            }
          ]
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"2\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/7fc81edb-6393-4562-b5be-17060362d97b",
        "resource": {
          "resourceType": "Observation",
          "id": "7fc81edb-6393-4562-b5be-17060362d97b",
          "meta": {
            "versionId": "2",
            "lastUpdated": "2019-06-05T02:55:34.118-04:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "8302-2",
                "display": "Body Height"
              }
            ],
            "text": "Body Height"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/040b39d3-7162-4d4d-9133-1eb0d2d3df35"
          },
          "effectiveDateTime": "2009-10-03T11:07:51-04:00",
          "issued": "2009-10-03T11:07:51.313-04:00",
          "valueQuantity": {
            "value": 135.73957089834354,
            "unit": "cm",
            "system": "http://unitsofmeasure.org",
            "code": "cm"
          }
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"2\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/Observation/997170c2-261d-42a3-8131-c88abedf357c",
        "resource": {
          "resourceType": "Observation",
          "id": "997170c2-261d-42a3-8131-c88abedf357c",
          "meta": {
            "versionId": "7",
            "lastUpdated": "2021-03-08T01:59:25.095-05:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "final",
          "category": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                  "code": "vital-signs",
                  "display": "vital-signs"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "29463-7",
                "display": "Body Weight"
              }
            ],
            "text": "Body Weight"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/040b39d3-7162-4d4d-9133-1eb0d2d3df35"
          },
          "effectiveDateTime": "2009-10-03T11:07:51-04:00",
          "issued": "2009-10-03T11:07:51.313-04:00",
          "valueQuantity": {
            "value": 31.489263570932035,
            "unit": "kg",
            "system": "http://unitsofmeasure.org",
            "code": "kg"
          }
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"7\""
        }
      }
    ]
  },
  medicationRequest: {
    "resourceType": "Bundle",
    "id": "f4d59dfd-7108-442d-90c4-4682875feca7",
    "meta": {
      "lastUpdated": "2021-03-26T20:48:33.147-04:00"
    },
    "type": "searchset",
    "total": 3,
    "link": [
      {
        "relation": "self",
        "url": "https://launch.smarthealthit.org/v/r4/fhir/MedicationRequest?patient=bc6c8e2a-63de-4790-94af-fcab57874c21"
      }
    ],
    "entry": [
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/MedicationRequest/b79244c3-1e9c-4cd9-b514-4e0b111758c8",
        "resource": {
          "resourceType": "MedicationRequest",
          "id": "b79244c3-1e9c-4cd9-b514-4e0b111758c8",
          "meta": {
            "versionId": "10",
            "lastUpdated": "2021-03-16T02:59:19.911-04:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "stopped",
          "intent": "order",
          "medicationCodeableConcept": {
            "coding": [
              {
                "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
                "code": "313782",
                "display": "Acetaminophen 325 MG Oral Tablet"
              }
            ],
            "text": "Acetaminophen 325 MG Oral Tablet"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/6d23f21c-6bbb-48d1-a40b-7779384eac79"
          },
          "authoredOn": "2018-10-26T11:07:51-04:00",
          "requester": {
            "reference": "Practitioner/ed34bab9-9639-452d-bf7a-b1cbace13733"
          },
          "reasonReference": [
            {
              "reference": "Condition/30cf7b77-ea5c-4d73-b7bf-df0d2ee5db3f"
            }
          ]
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"10\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/MedicationRequest/16fb9e81-ecf0-4d33-9c90-697fea77ed75",
        "resource": {
          "resourceType": "MedicationRequest",
          "id": "16fb9e81-ecf0-4d33-9c90-697fea77ed75",
          "meta": {
            "versionId": "4",
            "lastUpdated": "2021-03-16T02:58:43.286-04:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "stopped",
          "intent": "order",
          "medicationCodeableConcept": {
            "coding": [
              {
                "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
                "code": "748856",
                "display": "Yaz 28 Day Pack"
              }
            ],
            "text": "Yaz 28 Day Pack"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/fcb477e1-1513-4d1d-b8f4-adfdb6c619cf"
          },
          "authoredOn": "2014-11-04T10:07:51-05:00",
          "requester": {
            "reference": "Practitioner/7f01c91e-c9a8-453b-aba3-7ebb55556199"
          }
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"4\""
        }
      },
      {
        "fullUrl": "https://launch.smarthealthit.org/v/r4/fhir/MedicationRequest/2753d6b1-0a24-427d-8a32-4aad8e581a53",
        "resource": {
          "resourceType": "MedicationRequest",
          "id": "2753d6b1-0a24-427d-8a32-4aad8e581a53",
          "meta": {
            "versionId": "5",
            "lastUpdated": "2021-03-16T02:56:45.274-04:00",
            "tag": [
              {
                "system": "https://smarthealthit.org/tags",
                "code": "synthea-5-2019"
              }
            ]
          },
          "status": "stopped",
          "intent": "order",
          "medicationCodeableConcept": {
            "coding": [
              {
                "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
                "code": "751905",
                "display": "Trinessa 28 Day Pack"
              }
            ],
            "text": "Trinessa 28 Day Pack"
          },
          "subject": {
            "reference": "Patient/bc6c8e2a-63de-4790-94af-fcab57874c21"
          },
          "encounter": {
            "reference": "Encounter/091ffa01-5698-4700-8ddd-4144476ce4ac"
          },
          "authoredOn": "2015-10-30T11:07:51-04:00",
          "requester": {
            "reference": "Practitioner/7f01c91e-c9a8-453b-aba3-7ebb55556199"
          }
        },
        "search": {
          "mode": "match"
        },
        "response": {
          "status": "200 OK",
          "etag": "W/\"5\""
        }
      }
    ]
  }
};
