/*
  Saved responses from below API calls:
  https://launch.smarthealthit.org/v/r4/fhir/Patient/2cda5aad-e409-4070-9a15-e1c35c46ed5a
  https://launch.smarthealthit.org/v/r4/fhir/Observation?patient=2cda5aad-e409-4070-9a15-e1c35c46ed5a&_count=100&_sort=-date&code=http%3A%2F%2Floinc.org%7C8462-4%2Chttp%3A%2F%2Floinc.org%7C8480-6%2Chttp%3A%2F%2Floinc.org%7C2085-9%2Chttp%3A%2F%2Floinc.org%7C2089-1%2Chttp%3A%2F%2Floinc.org%7C55284-4%2Chttp%3A%2F%2Floinc.org%7C3141-9%2Chttp%3A%2F%2Floinc.org%7C8302-2%2Chttp%3A%2F%2Floinc.org%7C29463-7
  https://launch.smarthealthit.org/v/r4/fhir/MedicationRequest?patient=2cda5aad-e409-4070-9a15-e1c35c46ed5a
*/

export const geoffreyAbbottFhir = {
  patient: {
    resourceType: "Patient",
    id: "2cda5aad-e409-4070-9a15-e1c35c46ed5a",
    meta: {
      versionId: "16",
      lastUpdated: "2020-11-27T02:06:09.058-05:00",
      tag: [
        {
          system: "https://smarthealthit.org/tags",
          code: "synthea-5-2019",
        },
      ],
    },
    text: {
      status: "generated",
      div:
        '<div xmlns="http://www.w3.org/1999/xhtml">Generated by <a href="https://github.com/synthetichealth/synthea">Synthea</a>.Version identifier: v2.4.0-100-g26a4b936\n .   Person seed: -820587054795986734  Population seed: 1559319163074</div>',
    },
    extension: [
      {
        url: "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race",
        extension: [
          {
            url: "ombCategory",
            valueCoding: {
              system: "urn:oid:2.16.840.1.113883.6.238",
              code: "2106-3",
              display: "White",
            },
          },
          {
            url: "text",
            valueString: "White",
          },
        ],
      },
      {
        url:
          "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity",
        extension: [
          {
            url: "ombCategory",
            valueCoding: {
              system: "urn:oid:2.16.840.1.113883.6.238",
              code: "2186-5",
              display: "Not Hispanic or Latino",
            },
          },
          {
            url: "text",
            valueString: "Not Hispanic or Latino",
          },
        ],
      },
      {
        url:
          "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
        valueString: "Jenny Hermiston",
      },
      {
        url: "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex",
        valueCode: "M",
      },
      {
        url: "http://hl7.org/fhir/StructureDefinition/patient-birthPlace",
        valueAddress: {
          city: "Hopkinton",
          state: "Massachusetts",
          country: "US",
        },
      },
      {
        url:
          "http://synthetichealth.github.io/synthea/disability-adjusted-life-years",
        valueDecimal: 0.5458769044385493,
      },
      {
        url:
          "http://synthetichealth.github.io/synthea/quality-adjusted-life-years",
        valueDecimal: 27.45412309556145,
      },
    ],
    identifier: [
      {
        system: "https://github.com/synthetichealth/synthea",
        value: "73a7d6b7-0310-4fff-9b0b-7891a5e390f5",
      },
      {
        type: {
          coding: [
            {
              system: "http://terminology.hl7.org/CodeSystem/v2-0203",
              code: "MR",
              display: "Medical Record Number",
            },
          ],
          text: "Medical Record Number",
        },
        system: "http://hospital.smarthealthit.org",
        value: "73a7d6b7-0310-4fff-9b0b-7891a5e390f5",
      },
      {
        type: {
          coding: [
            {
              system: "http://terminology.hl7.org/CodeSystem/v2-0203",
              code: "SS",
              display: "Social Security Number",
            },
          ],
          text: "Social Security Number",
        },
        system: "http://hl7.org/fhir/sid/us-ssn",
        value: "999-91-2751",
      },
      {
        type: {
          coding: [
            {
              system: "http://terminology.hl7.org/CodeSystem/v2-0203",
              code: "DL",
              display: "Driver's License",
            },
          ],
          text: "Driver's License",
        },
        system: "urn:oid:2.16.840.1.113883.4.3.25",
        value: "S99987436",
      },
      {
        type: {
          coding: [
            {
              system: "http://terminology.hl7.org/CodeSystem/v2-0203",
              code: "PPN",
              display: "Passport Number",
            },
          ],
          text: "Passport Number",
        },
        system:
          "http://standardhealthrecord.org/fhir/StructureDefinition/passportNumber",
        value: "X60445896X",
      },
    ],
    name: [
      {
        use: "official",
        family: "Abbott",
        given: ["Geoffrey"],
        prefix: ["Mr."],
      },
    ],
    telecom: [
      {
        system: "phone",
        value: "555-514-6152",
        use: "home",
      },
    ],
    gender: "male",
    birthDate: "1990-09-01",
    address: [
      {
        extension: [
          {
            url: "http://hl7.org/fhir/StructureDefinition/geolocation",
            extension: [
              {
                url: "latitude",
                valueDecimal: 42.299625,
              },
              {
                url: "longitude",
                valueDecimal: -71.52842700000002,
              },
            ],
          },
        ],
        line: ["997 Koepp Row Unit 64"],
        city: "Southborough",
        state: "Massachusetts",
        postalCode: "01772",
        country: "US",
      },
    ],
    maritalStatus: {
      coding: [
        {
          system: "http://terminology.hl7.org/CodeSystem/v3-MaritalStatus",
          code: "M",
          display: "M",
        },
      ],
      text: "M",
    },
    multipleBirthBoolean: false,
    communication: [
      {
        language: {
          coding: [
            {
              system: "urn:ietf:bcp:47",
              code: "en-US",
              display: "English",
            },
          ],
          text: "English",
        },
      },
    ],
  },
  observation: {
    resourceType: "Bundle",
    id: "90229b3e-b4f3-48e3-a9ab-279c909dfb77",
    meta: {
      lastUpdated: "2021-03-26T20:34:33.372-04:00",
    },
    type: "searchset",
    total: 15,
    link: [
      {
        relation: "self",
        url:
          "https://launch.smarthealthit.org/v/r4/fhir/Observation?_count=100&_sort=-date&code=http%3A%2F%2Floinc.org%7C8462-4%2Chttp%3A%2F%2Floinc.org%7C8480-6%2Chttp%3A%2F%2Floinc.org%7C2085-9%2Chttp%3A%2F%2Floinc.org%7C2089-1%2Chttp%3A%2F%2Floinc.org%7C55284-4%2Chttp%3A%2F%2Floinc.org%7C3141-9%2Chttp%3A%2F%2Floinc.org%7C8302-2%2Chttp%3A%2F%2Floinc.org%7C29463-7&patient=2cda5aad-e409-4070-9a15-e1c35c46ed5a",
      },
    ],
    entry: [
      {
        fullUrl:
          "https://launch.smarthealthit.org/v/r4/fhir/Observation/b0948605-aa96-4a64-b448-d4254365284d",
        resource: {
          resourceType: "Observation",
          id: "b0948605-aa96-4a64-b448-d4254365284d",
          meta: {
            versionId: "297",
            lastUpdated: "2021-03-21T02:57:30.686-04:00",
            tag: [
              {
                system: "https://smarthealthit.org/tags",
                code: "synthea-5-2019",
              },
            ],
          },
          status: "final",
          category: [
            {
              coding: [
                {
                  system:
                    "http://terminology.hl7.org/CodeSystem/observation-category",
                  code: "vital-signs",
                  display: "vital-signs",
                },
              ],
            },
          ],
          code: {
            coding: [
              {
                system: "http://loinc.org",
                code: "29463-7",
                display: "Body Weight",
              },
            ],
            text: "Body Weight",
          },
          subject: {
            reference: "Patient/2cda5aad-e409-4070-9a15-e1c35c46ed5a",
          },
          encounter: {
            reference: "Encounter/1e38b771-ea87-4343-a5a8-60022374cbaa",
          },
          effectiveDateTime: "2017-07-15T05:51:38-04:00",
          issued: "2017-07-15T05:51:38.447-04:00",
          valueQuantity: {
            value: 73.6117147858519,
            unit: "kg",
            system: "http://unitsofmeasure.org",
            code: "kg",
          },
        },
        search: {
          mode: "match",
        },
        response: {
          status: "200 OK",
          etag: 'W/"297"',
        },
      },
      {
        fullUrl:
          "https://launch.smarthealthit.org/v/r4/fhir/Observation/b049279a-7ac7-4a5e-ae5a-2a5e7d0876f3",
        resource: {
          resourceType: "Observation",
          id: "b049279a-7ac7-4a5e-ae5a-2a5e7d0876f3",
          meta: {
            versionId: "20",
            lastUpdated: "2021-03-25T03:00:13.908-04:00",
            tag: [
              {
                system: "https://smarthealthit.org/tags",
                code: "synthea-5-2019",
              },
            ],
          },
          status: "final",
          category: [
            {
              coding: [
                {
                  system:
                    "http://terminology.hl7.org/CodeSystem/observation-category",
                  code: "vital-signs",
                  display: "vital-signs",
                },
              ],
            },
          ],
          code: {
            coding: [
              {
                system: "http://loinc.org",
                code: "55284-4",
                display: "Blood Pressure",
              },
            ],
            text: "Blood Pressure",
          },
          subject: {
            reference: "Patient/2cda5aad-e409-4070-9a15-e1c35c46ed5a",
          },
          encounter: {
            reference: "Encounter/1e38b771-ea87-4343-a5a8-60022374cbaa",
          },
          effectiveDateTime: "2017-07-15T05:51:38-04:00",
          issued: "2017-07-15T05:51:38.447-04:00",
          component: [
            {
              code: {
                coding: [
                  {
                    system: "http://loinc.org",
                    code: "8462-4",
                    display: "Diastolic Blood Pressure",
                  },
                ],
                text: "Diastolic Blood Pressure",
              },
              valueQuantity: {
                value: 116.3585493269368,
                unit: "mm[Hg]",
                system: "http://unitsofmeasure.org",
                code: "mm[Hg]",
              },
            },
            {
              code: {
                coding: [
                  {
                    system: "http://loinc.org",
                    code: "8480-6",
                    display: "Systolic Blood Pressure",
                  },
                ],
                text: "Systolic Blood Pressure",
              },
              valueQuantity: {
                value: 193.57441248970937,
                unit: "mm[Hg]",
                system: "http://unitsofmeasure.org",
                code: "mm[Hg]",
              },
            },
          ],
        },
        search: {
          mode: "match",
        },
        response: {
          status: "200 OK",
          etag: 'W/"20"',
        },
      },
      {
        fullUrl:
          "https://launch.smarthealthit.org/v/r4/fhir/Observation/f0ded9e0-451f-4160-a451-b207b84c620d",
        resource: {
          resourceType: "Observation",
          id: "f0ded9e0-451f-4160-a451-b207b84c620d",
          meta: {
            versionId: "7",
            lastUpdated: "2020-10-04T02:56:59.131-04:00",
            tag: [
              {
                system: "https://smarthealthit.org/tags",
                code: "synthea-5-2019",
              },
            ],
          },
          status: "final",
          category: [
            {
              coding: [
                {
                  system:
                    "http://terminology.hl7.org/CodeSystem/observation-category",
                  code: "vital-signs",
                  display: "vital-signs",
                },
              ],
            },
          ],
          code: {
            coding: [
              {
                system: "http://loinc.org",
                code: "8302-2",
                display: "Body Height",
              },
            ],
            text: "Body Height",
          },
          subject: {
            reference: "Patient/2cda5aad-e409-4070-9a15-e1c35c46ed5a",
          },
          encounter: {
            reference: "Encounter/1e38b771-ea87-4343-a5a8-60022374cbaa",
          },
          effectiveDateTime: "2017-07-15T05:51:38-04:00",
          issued: "2017-07-15T05:51:38.447-04:00",
          valueQuantity: {
            value: 171.7171907692734,
            unit: "cm",
            system: "http://unitsofmeasure.org",
            code: "cm",
          },
        },
        search: {
          mode: "match",
        },
        response: {
          status: "200 OK",
          etag: 'W/"7"',
        },
      },
      {
        fullUrl:
          "https://launch.smarthealthit.org/v/r4/fhir/Observation/836f51ea-c71a-4ff0-9667-68ef25e64617",
        resource: {
          resourceType: "Observation",
          id: "836f51ea-c71a-4ff0-9667-68ef25e64617",
          meta: {
            versionId: "14",
            lastUpdated: "2020-10-14T03:08:00.701-04:00",
            tag: [
              {
                system: "https://smarthealthit.org/tags",
                code: "synthea-5-2019",
              },
            ],
          },
          status: "final",
          category: [
            {
              coding: [
                {
                  system:
                    "http://terminology.hl7.org/CodeSystem/observation-category",
                  code: "vital-signs",
                  display: "vital-signs",
                },
              ],
            },
          ],
          code: {
            coding: [
              {
                system: "http://loinc.org",
                code: "29463-7",
                display: "Body Weight",
              },
            ],
            text: "Body Weight",
          },
          subject: {
            reference: "Patient/2cda5aad-e409-4070-9a15-e1c35c46ed5a",
          },
          encounter: {
            reference: "Encounter/ab2559be-0c83-47a9-b598-8a364d1feae5",
          },
          effectiveDateTime: "2014-07-12T05:51:38-04:00",
          issued: "2014-07-12T05:51:38.447-04:00",
          valueQuantity: {
            value: 69.40890499167166,
            unit: "kg",
            system: "http://unitsofmeasure.org",
            code: "kg",
          },
        },
        search: {
          mode: "match",
        },
        response: {
          status: "200 OK",
          etag: 'W/"14"',
        },
      },
      {
        fullUrl:
          "https://launch.smarthealthit.org/v/r4/fhir/Observation/9393c2e1-5d53-4a45-aa8c-0461a6c45340",
        resource: {
          resourceType: "Observation",
          id: "9393c2e1-5d53-4a45-aa8c-0461a6c45340",
          meta: {
            versionId: "7",
            lastUpdated: "2020-10-03T03:00:59.822-04:00",
            tag: [
              {
                system: "https://smarthealthit.org/tags",
                code: "synthea-5-2019",
              },
            ],
          },
          status: "final",
          category: [
            {
              coding: [
                {
                  system:
                    "http://terminology.hl7.org/CodeSystem/observation-category",
                  code: "vital-signs",
                  display: "vital-signs",
                },
              ],
            },
          ],
          code: {
            coding: [
              {
                system: "http://loinc.org",
                code: "55284-4",
                display: "Blood Pressure",
              },
            ],
            text: "Blood Pressure",
          },
          subject: {
            reference: "Patient/2cda5aad-e409-4070-9a15-e1c35c46ed5a",
          },
          encounter: {
            reference: "Encounter/ab2559be-0c83-47a9-b598-8a364d1feae5",
          },
          effectiveDateTime: "2014-07-12T05:51:38-04:00",
          issued: "2014-07-12T05:51:38.447-04:00",
          component: [
            {
              code: {
                coding: [
                  {
                    system: "http://loinc.org",
                    code: "8462-4",
                    display: "Diastolic Blood Pressure",
                  },
                ],
                text: "Diastolic Blood Pressure",
              },
              valueQuantity: {
                value: 98.854547028174,
                unit: "mm[Hg]",
                system: "http://unitsofmeasure.org",
                code: "mm[Hg]",
              },
            },
            {
              code: {
                coding: [
                  {
                    system: "http://loinc.org",
                    code: "8480-6",
                    display: "Systolic Blood Pressure",
                  },
                ],
                text: "Systolic Blood Pressure",
              },
              valueQuantity: {
                value: 152.43980902992823,
                unit: "mm[Hg]",
                system: "http://unitsofmeasure.org",
                code: "mm[Hg]",
              },
            },
          ],
        },
        search: {
          mode: "match",
        },
        response: {
          status: "200 OK",
          etag: 'W/"7"',
        },
      },
      {
        fullUrl:
          "https://launch.smarthealthit.org/v/r4/fhir/Observation/97b40532-bc62-45ad-bd87-300c143a9449",
        resource: {
          resourceType: "Observation",
          id: "97b40532-bc62-45ad-bd87-300c143a9449",
          meta: {
            versionId: "5",
            lastUpdated: "2020-10-03T03:00:38.731-04:00",
            tag: [
              {
                system: "https://smarthealthit.org/tags",
                code: "synthea-5-2019",
              },
            ],
          },
          status: "final",
          category: [
            {
              coding: [
                {
                  system:
                    "http://terminology.hl7.org/CodeSystem/observation-category",
                  code: "vital-signs",
                  display: "vital-signs",
                },
              ],
            },
          ],
          code: {
            coding: [
              {
                system: "http://loinc.org",
                code: "8302-2",
                display: "Body Height",
              },
            ],
            text: "Body Height",
          },
          subject: {
            reference: "Patient/2cda5aad-e409-4070-9a15-e1c35c46ed5a",
          },
          encounter: {
            reference: "Encounter/ab2559be-0c83-47a9-b598-8a364d1feae5",
          },
          effectiveDateTime: "2014-07-12T05:51:38-04:00",
          issued: "2014-07-12T05:51:38.447-04:00",
          valueQuantity: {
            value: 171.7171907692734,
            unit: "cm",
            system: "http://unitsofmeasure.org",
            code: "cm",
          },
        },
        search: {
          mode: "match",
        },
        response: {
          status: "200 OK",
          etag: 'W/"5"',
        },
      },
      {
        fullUrl:
          "https://launch.smarthealthit.org/v/r4/fhir/Observation/5cedca06-b1de-4406-a2fc-0e920518a88d",
        resource: {
          resourceType: "Observation",
          id: "5cedca06-b1de-4406-a2fc-0e920518a88d",
          meta: {
            versionId: "5",
            lastUpdated: "2020-10-03T03:00:16.546-04:00",
            tag: [
              {
                system: "https://smarthealthit.org/tags",
                code: "synthea-5-2019",
              },
            ],
          },
          status: "final",
          category: [
            {
              coding: [
                {
                  system:
                    "http://terminology.hl7.org/CodeSystem/observation-category",
                  code: "vital-signs",
                  display: "vital-signs",
                },
              ],
            },
          ],
          code: {
            coding: [
              {
                system: "http://loinc.org",
                code: "8302-2",
                display: "Body Height",
              },
            ],
            text: "Body Height",
          },
          subject: {
            reference: "Patient/2cda5aad-e409-4070-9a15-e1c35c46ed5a",
          },
          encounter: {
            reference: "Encounter/ba5cf724-c122-429b-9cd9-3dd98e11d8f5",
          },
          effectiveDateTime: "2013-08-03T05:51:38-04:00",
          issued: "2013-08-03T05:51:38.447-04:00",
          valueQuantity: {
            value: 171.7171907692734,
            unit: "cm",
            system: "http://unitsofmeasure.org",
            code: "cm",
          },
        },
        search: {
          mode: "match",
        },
        response: {
          status: "200 OK",
          etag: 'W/"5"',
        },
      },
      {
        fullUrl:
          "https://launch.smarthealthit.org/v/r4/fhir/Observation/799e3671-610c-42db-ba98-15d6c12bf843",
        resource: {
          resourceType: "Observation",
          id: "799e3671-610c-42db-ba98-15d6c12bf843",
          meta: {
            versionId: "9",
            lastUpdated: "2020-10-06T02:58:45.342-04:00",
            tag: [
              {
                system: "https://smarthealthit.org/tags",
                code: "synthea-5-2019",
              },
            ],
          },
          status: "final",
          category: [
            {
              coding: [
                {
                  system:
                    "http://terminology.hl7.org/CodeSystem/observation-category",
                  code: "vital-signs",
                  display: "vital-signs",
                },
              ],
            },
          ],
          code: {
            coding: [
              {
                system: "http://loinc.org",
                code: "29463-7",
                display: "Body Weight",
              },
            ],
            text: "Body Weight",
          },
          subject: {
            reference: "Patient/2cda5aad-e409-4070-9a15-e1c35c46ed5a",
          },
          encounter: {
            reference: "Encounter/ba5cf724-c122-429b-9cd9-3dd98e11d8f5",
          },
          effectiveDateTime: "2013-08-03T05:51:38-04:00",
          issued: "2013-08-03T05:51:38.447-04:00",
          valueQuantity: {
            value: 68.31214711160455,
            unit: "kg",
            system: "http://unitsofmeasure.org",
            code: "kg",
          },
        },
        search: {
          mode: "match",
        },
        response: {
          status: "200 OK",
          etag: 'W/"9"',
        },
      },
      {
        fullUrl:
          "https://launch.smarthealthit.org/v/r4/fhir/Observation/86b596cb-9f4a-4af1-82a3-1b2b00bcedf5",
        resource: {
          resourceType: "Observation",
          id: "86b596cb-9f4a-4af1-82a3-1b2b00bcedf5",
          meta: {
            versionId: "5",
            lastUpdated: "2020-10-03T02:58:07.042-04:00",
            tag: [
              {
                system: "https://smarthealthit.org/tags",
                code: "synthea-5-2019",
              },
            ],
          },
          status: "final",
          category: [
            {
              coding: [
                {
                  system:
                    "http://terminology.hl7.org/CodeSystem/observation-category",
                  code: "vital-signs",
                  display: "vital-signs",
                },
              ],
            },
          ],
          code: {
            coding: [
              {
                system: "http://loinc.org",
                code: "55284-4",
                display: "Blood Pressure",
              },
            ],
            text: "Blood Pressure",
          },
          subject: {
            reference: "Patient/2cda5aad-e409-4070-9a15-e1c35c46ed5a",
          },
          encounter: {
            reference: "Encounter/ba5cf724-c122-429b-9cd9-3dd98e11d8f5",
          },
          effectiveDateTime: "2013-08-03T05:51:38-04:00",
          issued: "2013-08-03T05:51:38.447-04:00",
          component: [
            {
              code: {
                coding: [
                  {
                    system: "http://loinc.org",
                    code: "8462-4",
                    display: "Diastolic Blood Pressure",
                  },
                ],
                text: "Diastolic Blood Pressure",
              },
              valueQuantity: {
                value: 96.72894800822793,
                unit: "mm[Hg]",
                system: "http://unitsofmeasure.org",
                code: "mm[Hg]",
              },
            },
            {
              code: {
                coding: [
                  {
                    system: "http://loinc.org",
                    code: "8480-6",
                    display: "Systolic Blood Pressure",
                  },
                ],
                text: "Systolic Blood Pressure",
              },
              valueQuantity: {
                value: 149.66912475620327,
                unit: "mm[Hg]",
                system: "http://unitsofmeasure.org",
                code: "mm[Hg]",
              },
            },
          ],
        },
        search: {
          mode: "match",
        },
        response: {
          status: "200 OK",
          etag: 'W/"5"',
        },
      },
      {
        fullUrl:
          "https://launch.smarthealthit.org/v/r4/fhir/Observation/794f34cd-6fcb-4747-a292-5fdbc5de2ee5",
        resource: {
          resourceType: "Observation",
          id: "794f34cd-6fcb-4747-a292-5fdbc5de2ee5",
          meta: {
            versionId: "15",
            lastUpdated: "2020-10-05T03:02:00.716-04:00",
            tag: [
              {
                system: "https://smarthealthit.org/tags",
                code: "synthea-5-2019",
              },
            ],
          },
          status: "final",
          category: [
            {
              coding: [
                {
                  system:
                    "http://terminology.hl7.org/CodeSystem/observation-category",
                  code: "vital-signs",
                  display: "vital-signs",
                },
              ],
            },
          ],
          code: {
            coding: [
              {
                system: "http://loinc.org",
                code: "29463-7",
                display: "Body Weight",
              },
            ],
            text: "Body Weight",
          },
          subject: {
            reference: "Patient/2cda5aad-e409-4070-9a15-e1c35c46ed5a",
          },
          encounter: {
            reference: "Encounter/e2eec903-c520-4792-a9a6-03c1e7baab2f",
          },
          effectiveDateTime: "2010-07-31T05:51:38-04:00",
          issued: "2010-07-31T05:51:38.447-04:00",
          valueQuantity: {
            value: 63.931154366802694,
            unit: "kg",
            system: "http://unitsofmeasure.org",
            code: "kg",
          },
        },
        search: {
          mode: "match",
        },
        response: {
          status: "200 OK",
          etag: 'W/"15"',
        },
      },
      {
        fullUrl:
          "https://launch.smarthealthit.org/v/r4/fhir/Observation/0a048775-dc76-4a78-bcd4-636dbdbb0a96",
        resource: {
          resourceType: "Observation",
          id: "0a048775-dc76-4a78-bcd4-636dbdbb0a96",
          meta: {
            versionId: "5",
            lastUpdated: "2020-10-03T02:59:42.049-04:00",
            tag: [
              {
                system: "https://smarthealthit.org/tags",
                code: "synthea-5-2019",
              },
            ],
          },
          status: "final",
          category: [
            {
              coding: [
                {
                  system:
                    "http://terminology.hl7.org/CodeSystem/observation-category",
                  code: "vital-signs",
                  display: "vital-signs",
                },
              ],
            },
          ],
          code: {
            coding: [
              {
                system: "http://loinc.org",
                code: "8302-2",
                display: "Body Height",
              },
            ],
            text: "Body Height",
          },
          subject: {
            reference: "Patient/2cda5aad-e409-4070-9a15-e1c35c46ed5a",
          },
          encounter: {
            reference: "Encounter/e2eec903-c520-4792-a9a6-03c1e7baab2f",
          },
          effectiveDateTime: "2010-07-31T05:51:38-04:00",
          issued: "2010-07-31T05:51:38.447-04:00",
          valueQuantity: {
            value: 171.70172336263934,
            unit: "cm",
            system: "http://unitsofmeasure.org",
            code: "cm",
          },
        },
        search: {
          mode: "match",
        },
        response: {
          status: "200 OK",
          etag: 'W/"5"',
        },
      },
      {
        fullUrl:
          "https://launch.smarthealthit.org/v/r4/fhir/Observation/91eb9345-b93b-44f4-a3ff-c2f3af42cf96",
        resource: {
          resourceType: "Observation",
          id: "91eb9345-b93b-44f4-a3ff-c2f3af42cf96",
          meta: {
            versionId: "5",
            lastUpdated: "2020-10-03T02:58:12.918-04:00",
            tag: [
              {
                system: "https://smarthealthit.org/tags",
                code: "synthea-5-2019",
              },
            ],
          },
          status: "final",
          category: [
            {
              coding: [
                {
                  system:
                    "http://terminology.hl7.org/CodeSystem/observation-category",
                  code: "vital-signs",
                  display: "vital-signs",
                },
              ],
            },
          ],
          code: {
            coding: [
              {
                system: "http://loinc.org",
                code: "55284-4",
                display: "Blood Pressure",
              },
            ],
            text: "Blood Pressure",
          },
          subject: {
            reference: "Patient/2cda5aad-e409-4070-9a15-e1c35c46ed5a",
          },
          encounter: {
            reference: "Encounter/e2eec903-c520-4792-a9a6-03c1e7baab2f",
          },
          effectiveDateTime: "2010-07-31T05:51:38-04:00",
          issued: "2010-07-31T05:51:38.447-04:00",
          component: [
            {
              code: {
                coding: [
                  {
                    system: "http://loinc.org",
                    code: "8462-4",
                    display: "Diastolic Blood Pressure",
                  },
                ],
                text: "Diastolic Blood Pressure",
              },
              valueQuantity: {
                value: 91.26182890262493,
                unit: "mm[Hg]",
                system: "http://unitsofmeasure.org",
                code: "mm[Hg]",
              },
            },
            {
              code: {
                coding: [
                  {
                    system: "http://loinc.org",
                    code: "8480-6",
                    display: "Systolic Blood Pressure",
                  },
                ],
                text: "Systolic Blood Pressure",
              },
              valueQuantity: {
                value: 188.2946064769834,
                unit: "mm[Hg]",
                system: "http://unitsofmeasure.org",
                code: "mm[Hg]",
              },
            },
          ],
        },
        search: {
          mode: "match",
        },
        response: {
          status: "200 OK",
          etag: 'W/"5"',
        },
      },
      {
        fullUrl:
          "https://launch.smarthealthit.org/v/r4/fhir/Observation/8fc9de61-a00d-47b8-8926-b86437972624",
        resource: {
          resourceType: "Observation",
          id: "8fc9de61-a00d-47b8-8926-b86437972624",
          meta: {
            versionId: "13",
            lastUpdated: "2021-03-06T01:59:11.316-05:00",
            tag: [
              {
                system: "https://smarthealthit.org/tags",
                code: "synthea-5-2019",
              },
            ],
          },
          status: "final",
          category: [
            {
              coding: [
                {
                  system:
                    "http://terminology.hl7.org/CodeSystem/observation-category",
                  code: "vital-signs",
                  display: "vital-signs",
                },
              ],
            },
          ],
          code: {
            coding: [
              {
                system: "http://loinc.org",
                code: "29463-7",
                display: "Body Weight",
              },
            ],
            text: "Body Weight",
          },
          subject: {
            reference: "Patient/2cda5aad-e409-4070-9a15-e1c35c46ed5a",
          },
          encounter: {
            reference: "Encounter/ffbebef5-2bc6-42ed-9e45-5913752d72c4",
          },
          effectiveDateTime: "2009-07-25T05:51:38-04:00",
          issued: "2009-07-25T05:51:38.447-04:00",
          valueQuantity: {
            value: 62.57459471273339,
            unit: "kg",
            system: "http://unitsofmeasure.org",
            code: "kg",
          },
        },
        search: {
          mode: "match",
        },
        response: {
          status: "200 OK",
          etag: 'W/"13"',
        },
      },
      {
        fullUrl:
          "https://launch.smarthealthit.org/v/r4/fhir/Observation/5e464b62-2985-41ba-90bc-125d89b2fa68",
        resource: {
          resourceType: "Observation",
          id: "5e464b62-2985-41ba-90bc-125d89b2fa68",
          meta: {
            versionId: "5",
            lastUpdated: "2020-10-03T02:59:48.198-04:00",
            tag: [
              {
                system: "https://smarthealthit.org/tags",
                code: "synthea-5-2019",
              },
            ],
          },
          status: "final",
          category: [
            {
              coding: [
                {
                  system:
                    "http://terminology.hl7.org/CodeSystem/observation-category",
                  code: "vital-signs",
                  display: "vital-signs",
                },
              ],
            },
          ],
          code: {
            coding: [
              {
                system: "http://loinc.org",
                code: "55284-4",
                display: "Blood Pressure",
              },
            ],
            text: "Blood Pressure",
          },
          subject: {
            reference: "Patient/2cda5aad-e409-4070-9a15-e1c35c46ed5a",
          },
          encounter: {
            reference: "Encounter/ffbebef5-2bc6-42ed-9e45-5913752d72c4",
          },
          effectiveDateTime: "2009-07-25T05:51:38-04:00",
          issued: "2009-07-25T05:51:38.447-04:00",
          component: [
            {
              code: {
                coding: [
                  {
                    system: "http://loinc.org",
                    code: "8462-4",
                    display: "Diastolic Blood Pressure",
                  },
                ],
                text: "Diastolic Blood Pressure",
              },
              valueQuantity: {
                value: 113.94509882006795,
                unit: "mm[Hg]",
                system: "http://unitsofmeasure.org",
                code: "mm[Hg]",
              },
            },
            {
              code: {
                coding: [
                  {
                    system: "http://loinc.org",
                    code: "8480-6",
                    display: "Systolic Blood Pressure",
                  },
                ],
                text: "Systolic Blood Pressure",
              },
              valueQuantity: {
                value: 177.81481253025206,
                unit: "mm[Hg]",
                system: "http://unitsofmeasure.org",
                code: "mm[Hg]",
              },
            },
          ],
        },
        search: {
          mode: "match",
        },
        response: {
          status: "200 OK",
          etag: 'W/"5"',
        },
      },
      {
        fullUrl:
          "https://launch.smarthealthit.org/v/r4/fhir/Observation/c14b4d95-67b1-427a-9dfc-cd5311cd82fe",
        resource: {
          resourceType: "Observation",
          id: "c14b4d95-67b1-427a-9dfc-cd5311cd82fe",
          meta: {
            versionId: "5",
            lastUpdated: "2020-10-03T03:00:51.306-04:00",
            tag: [
              {
                system: "https://smarthealthit.org/tags",
                code: "synthea-5-2019",
              },
            ],
          },
          status: "final",
          category: [
            {
              coding: [
                {
                  system:
                    "http://terminology.hl7.org/CodeSystem/observation-category",
                  code: "vital-signs",
                  display: "vital-signs",
                },
              ],
            },
          ],
          code: {
            coding: [
              {
                system: "http://loinc.org",
                code: "8302-2",
                display: "Body Height",
              },
            ],
            text: "Body Height",
          },
          subject: {
            reference: "Patient/2cda5aad-e409-4070-9a15-e1c35c46ed5a",
          },
          encounter: {
            reference: "Encounter/ffbebef5-2bc6-42ed-9e45-5913752d72c4",
          },
          effectiveDateTime: "2009-07-25T05:51:38-04:00",
          issued: "2009-07-25T05:51:38.447-04:00",
          valueQuantity: {
            value: 171.43529167345355,
            unit: "cm",
            system: "http://unitsofmeasure.org",
            code: "cm",
          },
        },
        search: {
          mode: "match",
        },
        response: {
          status: "200 OK",
          etag: 'W/"5"',
        },
      },
    ],
  },
  medicationRequest: {
    resourceType: "Bundle",
    id: "770387cc-a01d-4fad-ba9b-d69b2acb13f7",
    meta: {
      lastUpdated: "2021-03-26T20:34:33.434-04:00",
    },
    type: "searchset",
    total: 3,
    link: [
      {
        relation: "self",
        url:
          "https://launch.smarthealthit.org/v/r4/fhir/MedicationRequest?patient=2cda5aad-e409-4070-9a15-e1c35c46ed5a",
      },
    ],
    entry: [
      {
        fullUrl:
          "https://launch.smarthealthit.org/v/r4/fhir/MedicationRequest/83b6c511-8b78-4fe2-b484-346ddee61933",
        resource: {
          resourceType: "MedicationRequest",
          id: "83b6c511-8b78-4fe2-b484-346ddee61933",
          meta: {
            versionId: "3",
            lastUpdated: "2019-06-06T03:26:43.390-04:00",
            tag: [
              {
                system: "https://smarthealthit.org/tags",
                code: "synthea-5-2019",
              },
            ],
          },
          status: "active",
          intent: "order",
          medicationCodeableConcept: {
            coding: [
              {
                system: "http://www.nlm.nih.gov/research/umls/rxnorm",
                code: "316049",
                display: "Hydrochlorothiazide 25 MG",
              },
            ],
            text: "Hydrochlorothiazide 25 MG",
          },
          subject: {
            reference: "Patient/2cda5aad-e409-4070-9a15-e1c35c46ed5a",
          },
          encounter: {
            reference: "Encounter/ffbebef5-2bc6-42ed-9e45-5913752d72c4",
          },
          authoredOn: "2009-07-25T05:51:38-04:00",
          requester: {
            reference: "Practitioner/8b85559d-27de-4d4b-bea7-5a715164cb60",
          },
          reasonReference: [
            {
              reference: "Condition/0dc3b17a-1180-4881-bbc3-6f2a399901ae",
            },
          ],
        },
        search: {
          mode: "match",
        },
        response: {
          status: "200 OK",
          etag: 'W/"3"',
        },
      },
      {
        fullUrl:
          "https://launch.smarthealthit.org/v/r4/fhir/MedicationRequest/f3a6c1f0-3896-4120-a186-920e593b305e",
        resource: {
          resourceType: "MedicationRequest",
          id: "f3a6c1f0-3896-4120-a186-920e593b305e",
          meta: {
            versionId: "3",
            lastUpdated: "2019-06-06T03:26:31.516-04:00",
            tag: [
              {
                system: "https://smarthealthit.org/tags",
                code: "synthea-5-2019",
              },
            ],
          },
          status: "stopped",
          intent: "order",
          medicationCodeableConcept: {
            coding: [
              {
                system: "http://www.nlm.nih.gov/research/umls/rxnorm",
                code: "562251",
                display: "Amoxicillin 250 MG / Clavulanate 125 MG Oral Tablet",
              },
            ],
            text: "Amoxicillin 250 MG / Clavulanate 125 MG Oral Tablet",
          },
          subject: {
            reference: "Patient/2cda5aad-e409-4070-9a15-e1c35c46ed5a",
          },
          encounter: {
            reference: "Encounter/25e95ec9-97e5-4385-8f56-b2bf6552f466",
          },
          authoredOn: "2012-12-02T04:51:38-05:00",
          requester: {
            reference: "Practitioner/8b85559d-27de-4d4b-bea7-5a715164cb60",
          },
          reasonReference: [
            {
              reference: "Condition/d918664d-21be-4ecd-b98e-1195fd1961ac",
            },
          ],
        },
        search: {
          mode: "match",
        },
        response: {
          status: "200 OK",
          etag: 'W/"3"',
        },
      },
      {
        fullUrl:
          "https://launch.smarthealthit.org/v/r4/fhir/MedicationRequest/d7977dfa-dd7d-4390-b525-12e758f28c7b",
        resource: {
          resourceType: "MedicationRequest",
          id: "d7977dfa-dd7d-4390-b525-12e758f28c7b",
          meta: {
            versionId: "3",
            lastUpdated: "2019-06-06T03:02:24.081-04:00",
            tag: [
              {
                system: "https://smarthealthit.org/tags",
                code: "synthea-5-2019",
              },
            ],
          },
          status: "stopped",
          intent: "order",
          medicationCodeableConcept: {
            coding: [
              {
                system: "http://www.nlm.nih.gov/research/umls/rxnorm",
                code: "562251",
                display: "Amoxicillin 250 MG / Clavulanate 125 MG Oral Tablet",
              },
            ],
            text: "Amoxicillin 250 MG / Clavulanate 125 MG Oral Tablet",
          },
          subject: {
            reference: "Patient/2cda5aad-e409-4070-9a15-e1c35c46ed5a",
          },
          encounter: {
            reference: "Encounter/1c93688c-eb1c-40c6-a334-cc303ad478ff",
          },
          authoredOn: "2014-11-26T04:51:38-05:00",
          requester: {
            reference: "Practitioner/8b85559d-27de-4d4b-bea7-5a715164cb60",
          },
          reasonReference: [
            {
              reference: "Condition/d918664d-21be-4ecd-b98e-1195fd1961ac",
            },
            {
              reference: "Condition/9ada3825-6def-4ed3-bd27-20dd3f14472d",
            },
            {
              reference: "Condition/088d38d6-6d8e-415c-9073-bae8e606ac06",
            },
            {
              reference: "Condition/fce21c43-e297-4af0-93ae-bf8268baa58c",
            },
          ],
        },
        search: {
          mode: "match",
        },
        response: {
          status: "200 OK",
          etag: 'W/"3"',
        },
      },
    ],
  },
};
